Harmonise les fichiers MarkDown et y ajoute des insécables
etalab/doc.data.gouv.fr pull request #58
Opened 2018-11-29 17:34 UTC by bboulesteix

Cette _pull-request_ est purement cosmétique :

– elle passe les fichiers MarkDown dans un _linter_ pour standardiser leur mise en forme (j’utilise [linter-markdown](https://atom.io/packages/linter-markdown) sous Atom) ;
– elle ajoute des espaces insécables devant certains caractères (` ?`, ` ;`, ` :`) pour éviter les signes de ponctuation orphelins en début de ligne.

2018-11-30 09:48 UTC, abulte requested changes
Il me semble que le _linter_ est un peu violent...

Désolé d'avoir répété le point sur les espaces dans les listes un *grand* nombre de fois, j'ai été pris dans une sorte d'escalade de l'engagement 😬. J'espère que ça pourra être utile si tu veux repasser sur chaque liste.

2018-11-30 09:48 UTC, abulte commented on articles/_a-propos/differences-utilisateur-organisatoion.md
> +-   mettre en ligne des données gratuitement ;
Pourquoi autant d'espaces entre le `-` et le début du texte ? 🤔

2018-11-30 09:48 UTC, abulte commented on articles/_faq/citoyen.md
> +-   publier un jeu de données ;
Idem sur les espaces. Je ne retrouve pas cette façon de faire ici d'ailleurs : https://github.com/etalab/etalab/blob/master/typographie.md.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/developpeur.md
> +-   une [API complète](https://www.data.gouv.fr/api/), documentée avec [Swagger](http://swagger.io/)
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/developpeur.md
> +Vous pouvez contribuer en suivant la documentation spécifique et en proposant des _pull-requests_.
Pendant qu'on y est je ne suis pas sûr que le `-` soit justifié sur _pull request_ https://help.github.com/articles/about-pull-requests/.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/producteur.md
> +-   Impôts locaux
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/producteur.md
> +-   Impôts locaux en Lorraine pour l’année 2012
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/producteur.md
> +-   Fichier détaillé des personnes morales, par département et par an
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/producteur.md
> +    -   systèmes de coordonnées,
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/producteur.md
> +    -   \`DR[xxx][nom de la région accents respectés, trait-d’union partout]`` :
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   TOC
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   La **DGFiP (Direction générale des finances publiques)** propose aux acheteurs publics soumis à la comptabilité publics (par exemple les collectivités) de faire remonter ces données via Hélios ([
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   structure **plateforme** : un jeu de données (`dataset` dans l’API) par plateforme de marchés (identifiée par son SIRET)
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   jeu de données pour une **plateforme** : Données essentielles des marchés publics - `{nom de la plateforme}`
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +    [L’arrêté du 14 avril 2017](https://www.legifrance.gouv.fr/eli/arrete/2017/4/14/ECFM1637256A/jo/texte), modifié par [l’arrêté du 27 juillet 2018](https://www.legifrance.gouv.fr/affichTexte.do?cid
On dirait qu'un _code block_ a sauté.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +    La structure des données est définie par [des schémas XML et JSON](https://github.com/etalab/format-commande-publique) qui appliquent les exigences des arrêtés.
Tabulation en trop.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +    Pour plus d’informations, vous pouvez consulter [la page thématique](https://www.economie.gouv.fr/daj/ouverture-des-donnees-commande-publique) sur le site de la Direction des Affaires Juridiques.
Tabulation en trop.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   `données-essentielles`
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +    {
Le _code block_ a sauté.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   `DECP` pour "données essentielles de la commande publique"
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   `xml` pour du XML
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   `application/xml` pour du XML
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   `siret` : SIRET de l’acheteur
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +1.  Récupérer la liste des ressources du jeu de données ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +    curl https://data.gouv.fr/api/1/datasets/<dataset id ou slug>
Le _code block_ a sauté.

2018-11-30 09:48 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +-   le SIRET des acheteurs (colonne `siretAcheteur`)
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   [la transformation des données](#transform)
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   le concours [Dataconnexions][], organisé par [Etalab][], qui récompense les projets les plus innovants réutilisant des données publiques ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   [Open Food Facts](https://www.data.gouv.fr/fr/datasets/produits-alimentaires-ingredients-nutrition-labels/)
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   Add column by fetching URL, avec l’expression
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   Add column by fetching URL, avec l’expression
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   Si il existe une colonne `CP` contenant le code postal:
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   Edition de lignes, de polygones et de formes.
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +-   Les personnes présentes sont les bonnes personnes : 3 participants, c’est cool, 100 participants, c’est cool.
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +[etalab]: https://www.etalab.gouv.fr
Je ne vois pas de modification de la casse au niveau des endroits où ces liens sont utilisés 🤔. Est-ce que ça marche toujours ? Est-ce qu'il ne faut pas rester cohérent de toute façon, même si ça marche ?

2018-11-30 09:48 UTC, abulte commented on articles/_faq/reutilisateur.md
> +[etalab]: https://www.etalab.gouv.fr
NB : remarque générale sur l'ensemble des fichiers.

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/creer-un-compte.md
> +-   mettre en ligne un jeu de données ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
De plus, il me semble que cette syntaxe de déclaration de liens ne marche pas dans notre cas, à vérifier. NB : remarque générale sur tous les fichiers.

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Ouvrez l’e-mail qui vous a été envoyé par `no-reply@data.gouv.fr` et cliquez sur le bouton **CONFIRMER MAINTENANT** qu’il contient.
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/supprimer-un-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/supprimer-un-compte.md
> +-   les jeux de données publiés et les réutilisations référencées ne seront plus associées au producteur ou à l’auteur ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +-   votre **image** de profil ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +-   ajouter ou modifier votre **image de profil**, en la survolant avec le pointeur de votre souris puis en cliquant sur **Changer** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  Vous créez un moissonneur sur data.gouv.fr pour nous demander de surveiller votre plateforme ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   Open Data Soft (ODS) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   votre propre compte, pour une publication à titre individuel, sous votre propre nom ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   **Mauvais nom** : Moissonneur de mon portail
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   **Mauvaise source** :  `data.angers.fr`
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  Cliquez sur le bouton **Voir dans l’administration** une fois votre moissonneur créé ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/difference-jeu-de-donnees-et-ressource.md
> +-   un titre (obligatoire) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/difference-jeu-de-donnees-et-ressource.md
> +-   un titre (obligatoire) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +-   jeux de données ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +| Critère du tri                  | Effet du tri                                                                                    |
Est-ce que l'ancienne syntaxe n'est pas plus lisible (en _raw_) ?

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   sous votre propre nom, à titre individuel ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **Mauvais titre** : Horaires des cars
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **Mauvais sigle** : I.R.V.E.
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   Que contient le jeu de données ? Combien y a-t-il de fichiers ?
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   votre couverture spatiale correspond à la France, car vos données couvrent l’ensemble du territoire ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **fichier principal** : désigne tous les fichiers qui contiennent vos données brutes ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez un fichier, vous ne pouvez pas modifier ce champ, car il s’agit alors de l’URL assignée par data.gouv.fr à votre ressource ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, vous n’avez rien à faire, car nous calculons la taille de votre ressource pour vous ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, nous détectons automatiquement son format, vous n’avez donc rien à faire ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, votre type MIME est pré-rempli, vous n’avez donc rien à faire ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, vous n’avez rien à faire, car la somme de contrôle est créée par data.gouv.fr ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   voir votre jeu de données sur data.gouv.fr en cliquant sur le bouton **Voir sur le site** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +1.  Naviguez jusqu’au bloc intitulé **Ressources** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/telecharger-une-ressource.md
> +1.  Naviguez jusqu’au jeu de données qui contient la ressource à télécharger ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/ajouter-un-utilisateur-a-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +-   publier des jeux de données ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +-   png ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +-   publier un jeu de données en son nom, en cliquant sur le bouton **Publiez un nouveau jeu de données** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/demander-a-rejoindre-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/demander-a-rejoindre-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/differences-administrateur-editeur-organisation.md
> +-   publier des jeux de données au nom de l’organisation ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/differences-administrateur-editeur-organisation.md
> +-   ajouter des utilisateurs à l’organisation ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/retirer-un-utilisateur-d-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_organisations/supprimer-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   donner de la visibilité à la réutilisation ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   la méthode de création de la réutilisation (les outils et traitements utilisés par exemple) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +1.  Saisissez leurs titre dans le champ **Trouver votre jeu de données** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   voir la réutilisation sur le site, en cliquant sur **Voir sur le site** ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Cliquez sur l’icône en forme de 8 penché qui se situe au bout de la ligne où se trouve le titre de la discussion ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Cliquez sur l’icône en forme de 8 penché qui se situe à côté de la date à laquelle le commentaire en question a été publié ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Rendez-vous au bas de la discussion ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/ouvrir-une-discussion.md
> +-   sur la page d’un jeu de données ;
Point espaces :-)

2018-11-30 09:48 UTC, abulte commented on articles/_reutilisations-et-discussions/ouvrir-une-discussion.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Point espaces :-)

2018-11-30 09:59 UTC, bboulesteix commented on articles/_a-propos/differences-utilisateur-organisatoion.md
> +-   mettre en ligne des données gratuitement ;
Bonne question. 🙂 C’est le comportement par défaut du _linter_. 🤷‍♂️ Cela dit, nous pouvons changer ce comportement par défaut, si nous le souhaitons, en modifiant [les règles appliquées par le linter](https://github.com/remarkjs/remark-lint#rules). Je n’ai pas d’avis sur le sujet.

Si je devais donner une réponse, je dirais que le linter ajoute **trois** espaces pour produire un retrait proche à ce qu’on obtient quand on ajoute un retrait dans un éditeur de texte ordinaire (1 cm environ). Dit autrement, c’est une manière de créer des listes propres, en les distinguant clairement des paragraphes, au moyen d’un retrait net.

J’ajoute que ces espaces n’ont pas d’influence sur l’aspect final du document. Quand le MarkDown est transformé en HTML par Jekyll, les trois espaces sont changés en une seule espace. Le _linter_ n’est là que pour harmoniser l’aspect visuel des fichiers au format MarkDown, il n’affecte pas le HTML produit à partir du MarkDown — heureusement d’ailleurs.

2018-11-30 10:01 UTC, bboulesteix commented on articles/_faq/citoyen.md
> +-   publier un jeu de données ;
C’est vrai. Mais les règles en question s’appliquent au document final, tel qu’affiché dans un navigateur. Nous parlons ici de fichiers de travail, des fichiers MarkDown censés être transformés en HTML.

2018-11-30 10:03 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
Je ne comprends pas ton commentaire. Quel est le problème ici ?

2018-11-30 10:06 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +Vous pouvez contribuer en suivant la documentation spécifique et en proposant des _pull-requests_.
Exact. Il n’y a pas de tiret en anglais entre _pull_ et _request_, tu as raison. Je pourrais m’en passer. Je crois que j’applique [la même règle](https://www.scribecho.fr/2015/02/27/orthographe-du-mot-start-up/) que pour le mot _start-up_ — qui s’écrit d’une traite en anglais mais prend un tiret en français. Pas sûr que ça soit si utile que ça. 🤔

2018-11-30 10:26 UTC, abulte commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
Idem au-dessus : les fameux espaces entre `-` et le texte.

2018-11-30 10:27 UTC, abulte commented on articles/_a-propos/differences-utilisateur-organisatoion.md
> +-   mettre en ligne des données gratuitement ;
Je serais d'avis de changer le comportement. C'est plus difficile à écrire et à maintenir "manuellement" avec ces espaces en plus. De plus, j'ai l'impression que le nombre d'espaces n'est pas toujours le même, parfois 2 et parfois 4...

2018-11-30 10:28 UTC, abulte commented on articles/_faq/citoyen.md
> +-   publier un jeu de données ;
Je comprends, mais je pense aussi que ce document peut servir de référence sur la manière d'écrire le Markdown, pas seulement sur le rendu que l'on attend.

2018-11-30 10:29 UTC, abulte commented on articles/_faq/developpeur.md
> +Vous pouvez contribuer en suivant la documentation spécifique et en proposant des _pull-requests_.
AMHA, soit pull-request, soit _pull request_. Il me semble que l'italique sert à "admettre" que c'est un mot anglais, donc autant l'écrire correctement en anglais dans ce cas.

2018-11-30 10:32 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
D’accord, mais quel est le problème ? Ces espaces n’affectent que le fichier MarkDown, qui est un fichier de travail et non pas le fichier final. En gros, ces espaces ne « cassent » rien. Cela dit, tu as le droit de trouver ça moche. 🙂 

Encore une fois, nous pourrions changer les règles du _linter_ pour lui demander de ne mettre qu’un espace entre le tiret et le texte. En tout cas, une chose est sûre : [le MarkDown tolère les espaces doubles ou triples](https://daringfireball.net/projects/markdown/syntax#list). Ce n’est pas un problème.

2018-11-30 10:40 UTC, abulte commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
Je ne prétends pas que ça casse le rendu. Je m'inquiète juste de la maintenabilité et de la cohérence de nos fichiers Markdown : https://github.com/etalab/doc.data.gouv.fr/pull/58#discussion_r237813335.

2018-11-30 10:41 UTC, abulte commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
Pour moi le Markdown est du code source et mérite donc certaines règle de mise en forme au-delà du résultat rendu.

2018-11-30 13:04 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +Vous pouvez contribuer en suivant la documentation spécifique et en proposant des _pull-requests_.
Ça me va. Vendu pour _pull request_, faute d’équivalent français.

2018-11-30 13:52 UTC, bboulesteix commented on articles/_a-propos/differences-utilisateur-organisatoion.md
> +-   mettre en ligne des données gratuitement ;
Je suis d’accord avec toi. 🙂 Disons qu’il y a [de bonnes raisons](http://www.cirosantilli.com/markdown-style-guide/#spaces-after-list-marker) de systématiquement mettre 3 espaces devant les éléments d’une liste, mais c’est un peu byzantin comme justification. Surtout, c’est trop peu en lien avec le comportement spontané des rédacteurs, comme tu le soulignes, à savoir : mettre une espace simple. 

J’ai changé de _linter_. [tidy-markdown](https://atom.io/packages/tidy-markdown) est plus souple. C’est mieux.

2018-11-30 13:54 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +-   [les informations relatives à l’API](#section-api) ;
> Pour moi le Markdown est du code source et mérite donc certaines règles de mise en forme au-delà du résultat rendu.

Je suis complètement d’accord avec ça. C’est justement la raison pour laquelle @noirbizarre a proposé que nous utilisions un _linter_ pour nos fichiers MarkDown — et si possible, le même. De cette manière, ils auront tous le même style, la même syntaxe.

2018-11-30 13:55 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé : espace `tab` remplacé par une espace `simple`. ✅

2018-11-30 13:55 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé : espace `tab` remplacé par une espace `simple`. ✅

2018-11-30 13:55 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé : espace `tab` remplacé par une espace `simple`. ✅

2018-11-30 13:55 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/ouvrir-une-discussion.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé : espace `tab` remplacé par une espace `simple`. ✅

2018-11-30 13:55 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/ouvrir-une-discussion.md
> +-   sur la page d’un jeu de données ;
Corrigé : espace `tab` remplacé par une espace `simple`. ✅

2018-11-30 13:55 UTC, bboulesteix commented on articles/_faq/developpeur.md
> +-   une [API complète](https://www.data.gouv.fr/api/), documentée avec [Swagger](http://swagger.io/)
Corrigé : espace `tab` remplacée par une espace `simple`. ✅

2018-11-30 13:56 UTC, bboulesteix commented on articles/_faq/citoyen.md
> +-   publier un jeu de données ;
Ça me va. J’ai changé de _linter_ pour en prendre un qui applique des règles proches de celle que nous appliquons spontanément à la main.

2018-11-30 14:37 UTC, abulte commented on articles/_faq/citoyen.md
> +-   publier un jeu de données ;
👍 🙏

2018-12-03 10:04 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +- vos **jeux de données**, c’est-à-dire les données que vous avez publiées en votre nom — les données publiées pour le compte d’une organisation n’apparaissent pas sur votre profil personnel ;
Je ne suis pas contre cette modification, je me demande juste pourquoi 🤔 Y'a-t-il une différence de rendu ? Les `--` étant plus faciles à taper dans un Markdown que `–`, je me pose la question.

2018-12-03 10:07 UTC, abulte commented on articles/_api/dataset-workflow.md
> +La suite des opérations s’appliquent sur le même jeu de données dont l’identifiant est `5bc04b2cff66bd680e499f4a` sur lequel vous avez les permissions nécéssaires à la modification. Ce jeu de données
Je sais que ce n'est pas l'objet de la PR mais `s/examples/exemples/` et `s/qui soit/qui est soit/`.

2018-12-03 10:07 UTC, abulte commented on articles/_api/dataset-workflow.md
> +Tant que le jeu de donnéesn’a pas été purgé, vous avez la possibilité de le restaurer:
s/donnéesn’/données n’/

2018-12-03 10:08 UTC, abulte commented on articles/_api/intro.md
> +Lorsque c’est possible, l’API répondra en JSON avec le format suivant:
s/suivant:/suivant :/

2018-12-03 10:09 UTC, bboulesteix commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +- vos **jeux de données**, c’est-à-dire les données que vous avez publiées en votre nom — les données publiées pour le compte d’une organisation n’apparaissent pas sur votre profil personnel ;
Oui, il y a une différence de rendu. Un `--` en MarkDown ne sera pas _automatiquement_ transformé en un `—` (tiret long) dans le HTML. Pour faire apparaître un tiret long dans le HTML, il faut donc mettre des tirets longs dans les fichiers MarkDown, d’où cette modification.

2018-12-03 10:11 UTC, abulte commented on articles/_api/tutoriel.md
> +Vous pouvez récupérer une liste d'organisations (filtrée ou non) ou une organisation unitaire. Lorsque vous récupérez un point d'accès, le nombre d'éléments par page par défaut est de 20\. Récupérons
D'où vient / à quoi sert ce `\` ?

2018-12-03 10:12 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +La suite des opérations s’appliquent sur le même jeu de données dont l’identifiant est `5bc04b2cff66bd680e499f4a` sur lequel vous avez les permissions nécéssaires à la modification. Ce jeu de données
Tu as raison, profitons-en pour corriger les coquilles qui traînent. C’est fait. ✅

2018-12-03 10:12 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +Tant que le jeu de donnéesn’a pas été purgé, vous avez la possibilité de le restaurer:
Corrigé, merci. ✅

2018-12-03 10:14 UTC, bboulesteix commented on articles/_api/intro.md
> +Lorsque c’est possible, l’API répondra en JSON avec le format suivant:
Corrigé, merci. ✅

2018-12-03 10:15 UTC, bboulesteix commented on articles/_api/tutoriel.md
> +Vous pouvez récupérer une liste d'organisations (filtrée ou non) ou une organisation unitaire. Lorsque vous récupérez un point d'accès, le nombre d'éléments par page par défaut est de 20\. Récupérons
Le _linter_ devait être raide. Je supprimer le `\`.

2018-12-03 10:16 UTC, abulte commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +- vos **jeux de données**, c’est-à-dire les données que vous avez publiées en votre nom — les données publiées pour le compte d’une organisation n’apparaissent pas sur votre profil personnel ;
Parfait dans ce cas ! 👍

2018-12-03 15:20 UTC, abulte reviewed
Je mélange un peu _scope_ de la PR et coquilles, désolé. Mais c'est pas si souvent qu'on a le temps de faire une bonne relecture de tout ça ;-) D'ailleurs toute la partie "aide à la réutilisation" est sérieusement datée, à revoir un jour, je crois qu'on se l'était déjà dit.

2018-12-03 15:20 UTC, abulte commented on articles/_api/dataset-workflow.md
> +- avec envoie d’un fichier, dit ressource locale
s/envoie/envoi/

2018-12-03 15:20 UTC, abulte commented on articles/_api/dataset-workflow.md
> +La ressource est automatiquement créée et il est possible de modifier à posteriori les metadonnées avec l’[API de mise à jour de ressource]({{ site.baseurl }}{% link _api/reference.md %}#/datasets/up
s/à posteriori/a posteriori/

2018-12-03 15:20 UTC, abulte commented on articles/_api/dataset-workflow.md
> +La suite des opérations s’appliquent sur le même jeu de données dont l’identifiant est `5bc04b2cff66bd680e499f4a` sur lequel vous avez les permissions nécéssaires à la modification. Ce jeu de données
s/qui soit/qui est soit/

2018-12-03 15:20 UTC, abulte commented on articles/_api/dataset-workflow.md
> +Le jeu de données est maintenant **marqué comme supprimé**, il reste visible uniquement par vous et les membres de votre organisation,ainsi que par l’équipe d’administrateur de data.gouv.fr. Il sera
s/,ainsi/, ainsi/

2018-12-03 15:20 UTC, abulte commented on articles/_api/intro.md
> +Les différents points d’entrée de l’API attendent du JSON (`application/json`) en entrée et renvoient du JSON en sortie. Les seules exceptions sont les points d’entrée qui gèrent l’upload de fichiers
s/fichiers:/fichiers /

2018-12-03 15:20 UTC, abulte commented on articles/_api/intro.md
> +À chaque fois que vous pouvez utiliser identifiant d’objet dans une URL de l’API, vous avez les choix suivants :
s/identifiant/un identifiant/

2018-12-03 15:20 UTC, abulte commented on articles/_api/intro.md
> +Vous n’avez pas à calculer vous-même les pages précédentes et suivantes puisque les URL sont disponible dans la réponse dans les attributs `previous_page` et `next_page`. Ils seront définis à `null`
s/disponible/disponibles/

2018-12-03 15:20 UTC, abulte commented on articles/_faq/developpeur.md
> +Vous pouvez contribuer en suivant la documentation spécifique et en proposant des _pull-requests_.
Je ne vois pas la modification 🤔

2018-12-03 15:20 UTC, abulte commented on articles/_faq/integrateur.md
> +subtitle: "Quelles sont les intégrations tierces rendues possibles\_?"
Que fait donc ce `\_` ? Peut-être quelque chose de très bien, je ne sais pas ;-)

2018-12-03 15:20 UTC, abulte commented on articles/_faq/integrateur.md
> +summary: "Quelles sont les intégrations tierces rendues possibles\_?"
Que fait donc ce `\_` ? Peut-être quelque chose de très bien, je ne sais pas ;-)

2018-12-03 15:20 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +title: "Comment remplir les obligations légales des profils d’acheteur\_?"
Que fait donc ce `\_` ? Peut-être quelque chose de très bien, je ne sais pas ;-)

2018-12-03 15:20 UTC, abulte commented on articles/_faq/producteur.md
> +subtitle: "Que faut-il savoir avant de publier des données\_?"
Que fait donc ce `\_` ? Peut-être quelque chose de très bien, je ne sais pas ;-)

2018-12-03 15:20 UTC, abulte commented on articles/_faq/producteur.md
> +summary: "Que faut-il savoir avant de publier des données\_?"
Que fait donc ce `\_` ? Peut-être quelque chose de très bien, je ne sais pas ;-)

2018-12-03 15:20 UTC, abulte commented on articles/_faq/producteur.md
>  Les ressources de votre jeu de données. Si votre jeu concerne plusieurs départements, plusieurs années, il est possible de publier autant de fichiers que vous le souhaitez. Pour autant, sachez que du
> toujours préférable de diffuser les fichiers les plus denses possibles

A faire dans une autre PR mais je ne crois pas que ce soit _toujours vrai_. Mieux vaut plusieurs fichiers exploitables et intelligemment découpés plutôt qu'un seul de plusieurs Go, il me semble.

2018-12-03 15:20 UTC, abulte commented on articles/_faq/producteur.md
> +Préciser ici, de manière optionnelle, les indications sur l’organisation effectivement productrice, par exemple SGMAP/Service X.
Peut-être prendre un autre exemple que SGMAP :-) SPM ?

2018-12-03 15:20 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +<http://files.data.gouv.fr/decp/{siret}/{année}/{mois}/{jour}/DECP-{siret}-{année}-{mois}-{jour}-{seq}.xml>
Je me demande si les `<>` ont un intérêt dans ce cas où l'URL n'existe pas 🤔

2018-12-03 15:20 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +> <http://files.data.gouv.fr/decp/89764547841001/2018/11/28/DECP-89764547841001-2018-11-28-01.xml>
Je me demande si les `<>` ont un intérêt dans ce cas où nous sommes dans une citation 🤔

2018-12-03 15:20 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +> <https://data.gouv.fr/api/1/datasets/56cc6d6988ee385864fa79d0>
Je me demande si les `<>` ont un intérêt dans ce cas où nous sommes dans une citation 🤔

2018-12-03 15:20 UTC, abulte commented on articles/_faq/profils-d-acheteur.md
> +> <https://data.gouv.fr/api/1/datasets/referentiel-de-donnees-marches-publics>
Je me demande si les `<>` ont un intérêt dans ce cas où nous sommes dans une citation 🤔

2018-12-03 15:20 UTC, abulte commented on articles/_faq/reutilisateur.md
> +subtitle: "Que faire avec les données\_? Avec quels outils\_?"
Idem, que fait `\_` ici ?

2018-12-03 15:20 UTC, abulte commented on articles/_faq/reutilisateur.md
> +summary: "Que faire avec les données\_? Avec quels outils\_?"
Idem, que fait `\_` ici ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 1\. Définir qui publie les données moissonnées
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 2\. Configurer le moissonneur
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 3\. Demander la validation du moissonneur
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +------------------------------- | ------------------------------------------------------------------------------------
Pas fan de ce nouveau format 🤔 L'autre me parait plus pratique pour écrire. Mais pas bloquant pour moi.

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 1\. Définir qui publie les données
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 2\. Décrire votre jeu de données
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 3\. Importer vos fichiers
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 4\. Voir et compléter un jeu de données existant
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +### 1\. Éviter les doublons
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +### 2\. Décrire l’organisation
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_organisations/creer-une-organisation.md
> +### 3\. Ajouter un logo
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 1\. Choisir qui publie
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 2\. Décrire la réutilisation
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 3\. Associer des jeux de données à la réutilisation
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 4\. Insérer une image
Echappement (`\`) non nécessaire ?

2018-12-03 15:20 UTC, abulte commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 5\. Partager la réutilisation
Echappement (`\`) non nécessaire ?

2018-12-03 15:58 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 1\. Choisir qui publie
Oui, c’est n’importe quoi. 🤦‍♂️ Mais c’est maintenant corrigé. ✅

2018-12-03 15:58 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 2\. Décrire la réutilisation
Corrigé. ✅

2018-12-03 15:59 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 3\. Associer des jeux de données à la réutilisation
Corrigé. ✅

2018-12-03 15:59 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 5\. Partager la réutilisation
Corrigé. ✅

2018-12-03 15:59 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +## 4\. Insérer une image
Corrigé. ✅

2018-12-03 16:14 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +- avec envoie d’un fichier, dit ressource locale
Corrigé. ✅

2018-12-03 16:16 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +La ressource est automatiquement créée et il est possible de modifier à posteriori les metadonnées avec l’[API de mise à jour de ressource]({{ site.baseurl }}{% link _api/reference.md %}#/datasets/up
Corrigé. ✅

2018-12-03 16:16 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +La suite des opérations s’appliquent sur le même jeu de données dont l’identifiant est `5bc04b2cff66bd680e499f4a` sur lequel vous avez les permissions nécéssaires à la modification. Ce jeu de données
Corrigé. ✅

2018-12-03 16:17 UTC, bboulesteix commented on articles/_api/dataset-workflow.md
> +Le jeu de données est maintenant **marqué comme supprimé**, il reste visible uniquement par vous et les membres de votre organisation,ainsi que par l’équipe d’administrateur de data.gouv.fr. Il sera
Corrigé. ✅

2018-12-03 16:17 UTC, bboulesteix commented on articles/_api/intro.md
> +Les différents points d’entrée de l’API attendent du JSON (`application/json`) en entrée et renvoient du JSON en sortie. Les seules exceptions sont les points d’entrée qui gèrent l’upload de fichiers
Corrigé. ✅

2018-12-06 14:09 UTC, abulte commented on articles/_gestion-du-compte/creer-un-compte.md
> +1. Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
Est-ce que tu as pu tester que ça marchait bien ? Je me souviens avoir rédigé ce paragraphe, et la solution simple `<>` ne marchait pas sur doc.data.gouv.fr. Mais je m'étais peut-être gaufré à l'époque.

2018-12-06 14:10 UTC, bboulesteix commented on articles/_faq/producteur.md
> +-   Impôts locaux
Corrigé. ✅

2018-12-06 14:10 UTC, bboulesteix commented on articles/_faq/producteur.md
> +-   Fichier détaillé des personnes morales, par département et par an
Corrigé. ✅

2018-12-06 14:10 UTC, bboulesteix commented on articles/_faq/producteur.md
> +    -   \`DR[xxx][nom de la région accents respectés, trait-d’union partout]`` :
Corrigé. ✅

2018-12-06 14:10 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   La **DGFiP (Direction générale des finances publiques)** propose aux acheteurs publics soumis à la comptabilité publics (par exemple les collectivités) de faire remonter ces données via Hélios ([
Corrigé. ✅

2018-12-06 14:11 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +    [L’arrêté du 14 avril 2017](https://www.legifrance.gouv.fr/eli/arrete/2017/4/14/ECFM1637256A/jo/texte), modifié par [l’arrêté du 27 juillet 2018](https://www.legifrance.gouv.fr/affichTexte.do?cid
Il est toujours là. 🙂

2018-12-06 14:11 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +    Pour plus d’informations, vous pouvez consulter [la page thématique](https://www.economie.gouv.fr/daj/ouverture-des-donnees-commande-publique) sur le site de la Direction des Affaires Juridiques.
Corrigé. ✅

2018-12-06 14:11 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   `données-essentielles`
Corrigé. ✅

2018-12-06 14:11 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +    {
Corrigé. ✅

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   `DECP` pour "données essentielles de la commande publique"
Corrigé. ✅

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   `application/xml` pour du XML
Corrigé. ✅

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +1.  Récupérer la liste des ressources du jeu de données ;
Corrigé. ✅

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +    curl https://data.gouv.fr/api/1/datasets/<dataset id ou slug>
Il est toujours là.

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/producteur.md
> +-   Impôts locaux en Lorraine pour l’année 2012
Corrigé. ✅

2018-12-06 14:12 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   TOC
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   jeu de données pour une **plateforme** : Données essentielles des marchés publics - `{nom de la plateforme}`
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   structure **plateforme** : un jeu de données (`dataset` dans l’API) par plateforme de marchés (identifiée par son SIRET)
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/producteur.md
> +    -   systèmes de coordonnées,
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   `xml` pour du XML
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +-   le SIRET des acheteurs (colonne `siretAcheteur`)
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   [la transformation des données](#transform)
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   le concours [Dataconnexions][], organisé par [Etalab][], qui récompense les projets les plus innovants réutilisant des données publiques ;
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   [Open Food Facts](https://www.data.gouv.fr/fr/datasets/produits-alimentaires-ingredients-nutrition-labels/)
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   Add column by fetching URL, avec l’expression
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   Add column by fetching URL, avec l’expression
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   Si il existe une colonne `CP` contenant le code postal:
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   Edition de lignes, de polygones et de formes.
Corrigé. ✅

2018-12-06 14:13 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +-   Les personnes présentes sont les bonnes personnes : 3 participants, c’est cool, 100 participants, c’est cool.
Corrigé. ✅

2018-12-06 14:14 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +-   mettre en ligne un jeu de données ;
Corrigé. ✅

2018-12-06 14:16 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +[etalab]: https://www.etalab.gouv.fr
Tous les liens sont en minuscules. Tu dois parler d’une version périmée du fichier. Plus largement, tous les articles du dossier `_faq` sont amenés à être archivés.

2018-12-06 14:16 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
Oui, c’est byzantin comme façon d’écrire les URL. Mon nouveau _linter_ ne va pas aussi loin. 🙂

2018-12-06 14:18 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
Corrigé, donc. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_gestion-du-compte/supprimer-un-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +-   votre **image** de profil ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  Vous créez un moissonneur sur data.gouv.fr pour nous demander de surveiller votre plateforme ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +-   ajouter ou modifier votre **image de profil**, en la survolant avec le pointeur de votre souris puis en cliquant sur **Changer** ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:18 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   Open Data Soft (ODS) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_gestion-du-compte/voir-ou-modifier-votre-compte.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_gestion-du-compte/supprimer-un-compte.md
> +-   les jeux de données publiés et les réutilisations référencées ne seront plus associées au producteur ou à l’auteur ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +1.  Ouvrez l’e-mail qui vous a été envoyé par `no-reply@data.gouv.fr` et cliquez sur le bouton **CONFIRMER MAINTENANT** qu’il contient.
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   votre propre compte, pour une publication à titre individuel, sous votre propre nom ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   **Mauvais nom** : Moissonneur de mon portail
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +-   **Mauvaise source** :  `data.angers.fr`
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +1.  Cliquez sur le bouton **Voir dans l’administration** une fois votre moissonneur créé ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/difference-jeu-de-donnees-et-ressource.md
> +-   un titre (obligatoire) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/difference-jeu-de-donnees-et-ressource.md
> +-   un titre (obligatoire) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +-   jeux de données ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +| Critère du tri                  | Effet du tri                                                                                    |
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:19 UTC, bboulesteix commented on articles/_jeux-de-donnees/mettre-a-jour-un-jeu-de-donnees-ou-une-ressource.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   sous votre propre nom, à titre individuel ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **Mauvais titre** : Horaires des cars
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **Mauvais sigle** : I.R.V.E.
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   Que contient le jeu de données ? Combien y a-t-il de fichiers ?
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   votre couverture spatiale correspond à la France, car vos données couvrent l’ensemble du territoire ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   **fichier principal** : désigne tous les fichiers qui contiennent vos données brutes ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez un fichier, vous ne pouvez pas modifier ce champ, car il s’agit alors de l’URL assignée par data.gouv.fr à votre ressource ;
Corrigé. ✅

2018-12-06 14:20 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, vous n’avez rien à faire, car nous calculons la taille de votre ressource pour vous ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, nous détectons automatiquement son format, vous n’avez donc rien à faire ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, votre type MIME est pré-rempli, vous n’avez donc rien à faire ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   si vous importez votre fichier, vous n’avez rien à faire, car la somme de contrôle est créée par data.gouv.fr ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +-   voir votre jeu de données sur data.gouv.fr en cliquant sur le bouton **Voir sur le site** ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +1.  Naviguez jusqu’au bloc intitulé **Ressources** ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/supprimer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/telecharger-une-ressource.md
> +1.  Naviguez jusqu’au jeu de données qui contient la ressource à télécharger ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_jeux-de-donnees/transferer-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:21 UTC, bboulesteix commented on articles/_organisations/ajouter-un-utilisateur-a-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:23 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +-   publier des jeux de données ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +-   png ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +-   publier un jeu de données en son nom, en cliquant sur le bouton **Publiez un nouveau jeu de données** ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/demander-a-rejoindre-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/demander-a-rejoindre-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/differences-administrateur-editeur-organisation.md
> +-   publier des jeux de données au nom de l’organisation ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/differences-administrateur-editeur-organisation.md
> +-   ajouter des utilisateurs à l’organisation ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/retirer-un-utilisateur-d-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_organisations/supprimer-une-organisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   donner de la visibilité à la réutilisation ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   la méthode de création de la réutilisation (les outils et traitements utilisés par exemple) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +1.  Saisissez leurs titre dans le champ **Trouver votre jeu de données** ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/associer-une-reutilisation-a-un-jeu-de-donnees.md
> +-   voir la réutilisation sur le site, en cliquant sur **Voir sur le site** ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Cliquez sur l’icône en forme de 8 penché qui se situe au bout de la ligne où se trouve le titre de la discussion ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Cliquez sur l’icône en forme de 8 penché qui se situe à côté de la date à laquelle le commentaire en question a été publié ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  Rendez-vous au bas de la discussion ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/moderer-une-discussion.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:24 UTC, bboulesteix commented on articles/_reutilisations-et-discussions/modifier-ou-supprimer-une-reutilisation.md
> +1.  [Connectez-vous à votre compte](https://www.data.gouv.fr/fr/login) ;
Corrigé. ✅

2018-12-06 14:26 UTC, bboulesteix commented on articles/_api/intro.md
> +À chaque fois que vous pouvez utiliser identifiant d’objet dans une URL de l’API, vous avez les choix suivants :
Corrigé. ✅

2018-12-06 14:28 UTC, bboulesteix commented on articles/_api/intro.md
> +Vous n’avez pas à calculer vous-même les pages précédentes et suivantes puisque les URL sont disponible dans la réponse dans les attributs `previous_page` et `next_page`. Ils seront définis à `null`
Corrigé, merci. ✅

2018-12-06 14:28 UTC, bboulesteix commented on articles/_faq/integrateur.md
> +subtitle: "Quelles sont les intégrations tierces rendues possibles\_?"
Aucune idée. Je l’ai retiré.

2018-12-06 14:28 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +title: "Comment remplir les obligations légales des profils d’acheteur\_?"
Caractère retiré.

2018-12-06 14:28 UTC, bboulesteix commented on articles/_faq/producteur.md
> +summary: "Que faut-il savoir avant de publier des données\_?"
Supprimé.

2018-12-06 14:28 UTC, bboulesteix commented on articles/_faq/producteur.md
> +subtitle: "Que faut-il savoir avant de publier des données\_?"
Supprimé.

2018-12-06 14:29 UTC, bboulesteix commented on articles/_faq/integrateur.md
> +summary: "Quelles sont les intégrations tierces rendues possibles\_?"
Supprimé.

2018-12-06 14:30 UTC, bboulesteix commented on articles/_faq/producteur.md
>  Les ressources de votre jeu de données. Si votre jeu concerne plusieurs départements, plusieurs années, il est possible de publier autant de fichiers que vous le souhaitez. Pour autant, sachez que du
Les articles contenus dans le dossier `_faq` sont les articles « historiques ». J’ai prévu de les archiver dans quelques semaines.

2018-12-06 14:30 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +<http://files.data.gouv.fr/decp/{siret}/{année}/{mois}/{jour}/DECP-{siret}-{année}-{mois}-{jour}-{seq}.xml>
Le _linter_ n’a sans doute pas fait la différence. Problème corrigé. Chevrons supprimés.

2018-12-06 14:30 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +> <https://data.gouv.fr/api/1/datasets/56cc6d6988ee385864fa79d0>
Chevrons supprimés.

2018-12-06 14:30 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +> <https://data.gouv.fr/api/1/datasets/referentiel-de-donnees-marches-publics>
Chevrons supprimés.

2018-12-06 14:31 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +summary: "Que faire avec les données\_? Avec quels outils\_?"
Caractère supprimé.

2018-12-06 14:31 UTC, bboulesteix commented on articles/_faq/reutilisateur.md
> +subtitle: "Que faire avec les données\_? Avec quels outils\_?"
Caractère supprimé.

2018-12-06 14:31 UTC, bboulesteix commented on articles/_faq/profils-d-acheteur.md
> +> <http://files.data.gouv.fr/decp/89764547841001/2018/11/28/DECP-89764547841001-2018-11-28-01.xml>
Caractères supprimés.

2018-12-06 14:32 UTC, bboulesteix commented on articles/_faq/producteur.md
> +Préciser ici, de manière optionnelle, les indications sur l’organisation effectivement productrice, par exemple SGMAP/Service X.
Articles historiques, encore une fois, sur le point d’être archivés. Inutiles de les retoucher, à mon avis.

2018-12-06 14:32 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 1\. Définir qui publie les données moissonnées
Caractère supprimé.

2018-12-06 14:32 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 3\. Demander la validation du moissonneur
Caractère supprimé.

2018-12-06 14:33 UTC, bboulesteix commented on articles/_jeux-de-donnees/faire-une-recherche.md
> +------------------------------- | ------------------------------------------------------------------------------------
Oui, c’est moyen, mais ça reste lisible si tu n’appliques pas de `wrap` à tes lignes.

2018-12-06 14:33 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 1\. Définir qui publie les données
Supprimé.

2018-12-06 14:33 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 2\. Décrire votre jeu de données
Supprimé.

2018-12-06 14:33 UTC, bboulesteix commented on articles/_jeux-de-donnees/demander-a-datagouvfr-de-moisonner-votre-site.md
> +### 2\. Configurer le moissonneur
Supprimé.

2018-12-06 14:34 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 3\. Importer vos fichiers
Supprimé.

2018-12-06 14:34 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +### 1\. Éviter les doublons
Supprimé.

2018-12-06 14:34 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +### 3\. Ajouter un logo
Supprimé.

2018-12-06 14:34 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +1. Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
La question ne se pose plus, les chevrons ne sont plus en place. 🙂

2018-12-06 14:35 UTC, bboulesteix commented on articles/_jeux-de-donnees/publier-un-jeu-de-donnes.md
> +## 4\. Voir et compléter un jeu de données existant
Supprimé.

2018-12-06 14:37 UTC, bboulesteix commented on articles/_organisations/creer-une-organisation.md
> +### 2\. Décrire l’organisation
Supprimé.

2018-12-06 14:50 UTC, bboulesteix commented on articles/_gestion-du-compte/creer-un-compte.md
> +1. Rendez-vous sur : <https://www.data.gouv.fr/fr/register> ;
Je pense que ça marche, maintenant, en mettant des chevrons. Du moins ça marche en local, de mon côté. Quoi qu’il en soit, la question ne se pose plus, car les chevrons ne figurent plus dans l’article.

2018-12-06 14:58 UTC, abulte approved these changes
👏 

Est-ce qu'on peut documenter l'usage du _linter_ quelque part ? Genre sur la page Typographie de etalab/etalab ?

2018-12-06 15:24 UTC, bboulesteix commented
> Est-ce qu'on peut documenter l'usage du linter quelque part ? Genre sur la page Typographie de etalab/etalab ?

Pourquoi pas, oui, bonne idée. 👍 Même si, en gros, le _linter_ ne fait qu’appliquer un _styleguide_ MarkDown — en l’occurrence, celui de [prettier](https://github.com/prettier/prettier). 

Pour que le _linter_ soit vraiment utile, il ne devrait à mon avis passer sur nos textes qu’en bout de chaîne, à la toute fin, au moment du _build_, à la manière de [Travis](https://travis-ci.org) par exemple. De cette manière, nous aurions des fichiers cohérents à l’arrivée. C’est ce que permet de faire une application comme : https://github.com/apps/unibeautify-ci.

Nous pourrions aussi aller plus loin, et considérer qu’il est important d’avoir des fichiers source, c’est-à-dire des fichiers de travail (MarkDown) cohérents _aussi_. Ce qui impliquerait que nous utilisions tous _le même_ _linter_ dans nos éditeurs de texte respectifs.

Au total, nous avons donc le choix :

1. Ou bien nous adoptons tous _le même_ _linter_ dans nos éditeurs de texte ([prettier](https://github.com/prettier/prettier) donc) ;
2. Ou bien nous mettons en place une application comme [unibeautify-ci](https://github.com/apps/unibeautify-ci) en bout de chaîne ;
3. Ou bien nous faisons les deux (_linter_ dans l’éditeur et au moment du _build_) pour se blinder.

Si ces propositions te semblent raisonnables, @abulte, y en a-t-il une qui a ta préférence ?

2018-12-06 15:31 UTC, abulte commented
@bboulesteix La 3 me parait pas mal. Les profils techniques seront contents de produire du Markdown cohérent dès le début (et vérifier les éventuelles pétouilles) et les "autres" ne s'embêteront pas avec ça et produiront du Markdown cohérent sans même le savoir. En revanche il faut que le _linter_ dans l'éditeur et dans la _CI_ fasse **exactement** la même chose, sinon ça sera l'enfer.

S'il ne faut choisir qu'une seule option entre 1 et 2, ce serait 1 pour moi.

2018-12-06 15:31 UTC, abulte commented
@bboulesteix La 3 me parait pas mal. Les profils techniques seront contents de produire du Markdown cohérent dès le début (et vérifier les éventuelles pétouilles) et les "autres" ne s'embêteront pas avec ça et produiront du Markdown cohérent sans même le savoir. En revanche il faut que le _linter_ dans l'éditeur et dans la _CI_ fasse **exactement** la même chose, sinon ça sera l'enfer.

S'il ne faut choisir qu'une seule option entre 1 et 2, ce serait 1 pour moi.

2018-12-06 15:58 UTC, bboulesteix commented
Merci pour ta réponse @abulte.

> En revanche il faut que le linter dans l'éditeur et dans la CI fasse exactement la même chose, sinon ça sera l'enfer.

Tout à fait d’accord. La bonne nouvelle, c’est que c’est possible. 🎉 Car [unibeautify-ci](https://github.com/apps/unibeautify-ci) utilise [prettier](https://github.com/prettier/prettier) en guise de _styleguide_ pour sa moulinette MarkDown. 

Nous pouvons donc avoir :

- du [prettier](https://github.com/prettier/prettier) dans notre éditeur de texte, avec [atom-beautify](https://atom.io/packages/atom-beautify) par exemple (ce dernier n’utilise pas [prettier](https://github.com/prettier/prettier) par défaut, mais le propose [en option dans la configuration](https://github.com/Glavin001/atom-beautify/blob/v0.33.4/docs/options.md#markdown) du _package_) ;
- du [prettier](https://github.com/prettier/prettier) en bout de chaîne, avec [unibeautify-ci](https://github.com/apps/unibeautify-ci).

_Prettier all the thingz._ 🚀

2018-12-06 16:10 UTC, merged

2018-12-06 16:16 UTC, bboulesteix commented
Pour l’installation de https://github.com/apps/unibeautify-ci, j’ai créé #61, @abulte. Ce qui me permet de fermer cette _pull request_. Encore merci pour ton aide et tes conseils. 👏